version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "image-detection"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-axnhtz4b4276"
s3_prefix = "image-detection"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
