AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  goal-detector

  Sample SAM Template for goal detection

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10


Resources:
  
  BallDetectorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: detector/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSSMFullAccess
        - AmazonSageMakerFullAccess
        - AmazonSNSFullAccess
      Environment:
        Variables:
          GAME_STATS_TOPIC_ARN: 'arn:aws:sns:us-west-2:471222670403:cranebot22-game-stats-topic'
  

  BallDetectorFunctionInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref BallDetectorFunction
      Principal: iot.amazonaws.com
      SourceArn: arn:aws:iot:us-west-2:471222670403:rule/image_detection



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BallDetectorFunction:
    Description: "BallDetectorFunction Lambda Function ARN"
    Value: !GetAtt BallDetectorFunction.Arn
